# Generated by Django 6.0.7 on 2026-07-11 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattingStatLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_bats', models.PositiveSmallIntegerField(default=0)),
                ('hits', models.PositiveSmallIntegerField(default=0)),
                ('walks', models.PositiveSmallIntegerField(default=0)),
                ('runs', models.PositiveSmallIntegerField(default=0)),
                ('rbis', models.PositiveSmallIntegerField(default=0)),
                ('strikeouts', models.PositiveSmallIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_lines', to='games.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_lines', to='players.player')),
            ],
            options={
                'unique_together': {('player', 'game')},
            },
        ),
        migrations.CreateModel(
            name='PitchingStatLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings_pitched', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('earned_runs', models.PositiveSmallIntegerField(default=0)),
                ('walks_allowed', models.PositiveSmallIntegerField(default=0)),
                ('strikeouts', models.PositiveSmallIntegerField(default=0)),
                ('hits_allowed', models.PositiveSmallIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitching_lines', to='games.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitching_lines', to='players.player')),
            ],
            options={
                'unique_together': {('player', 'game')},
            },
        ),
    ]
