# Generated by Django 6.0.7 on 2026-07-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchingstatline',
            name='pitches_thrown',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pitchingstatline',
            name='runs_allowed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
