# Generated by Django 6.0.7 on 2026-08-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_pitchingstatline_pitches_thrown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battingstatline',
            name='doubles',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battingstatline',
            name='hit_by_pitch',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battingstatline',
            name='home_runs',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battingstatline',
            name='reached_on_error',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battingstatline',
            name='sacrifices',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battingstatline',
            name='singles',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battingstatline',
            name='stolen_bases',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battingstatline',
            name='triples',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
