# Generated by Django 6.0.7 on 2026-07-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
