# Generated by Django 6.0.7 on 2026-07-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('TBP', 'To be played'), ('W', 'Win'), ('L', 'Loss'), ('T', 'Tie'), ('CAN', 'Canceled'), ('PP', 'Postponed')], default='TBP', max_length=3),
        ),
    ]
