# Generated by Django 6.0.7 on 2026-07-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('F', 'Final'), ('TBP', 'To be played'), ('W', 'Win'), ('L', 'Loss'), ('T', 'Tie'), ('CAN', 'Canceled'), ('PPD', 'Postponed'), ('SPD', 'Suspended'), ('FFT', 'Forfeit')], default='TBP', max_length=3),
        ),
    ]
