# Generated by Django 6.0.7 on 2026-07-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='venue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
