# Generated by Django 6.0.7 on 2026-07-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_game_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='away_runs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='home_runs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='away_score',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='home_score',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
