# Generated by Django 6.0.7 on 2026-07-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_gameresult_away_runs_gameresult_home_runs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='away_errors',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='away_hits',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='home_errors',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='home_hits',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
