# Generated by Django 6.0.7 on 2026-07-18 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_gameresult_away_errors_gameresult_away_hits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameresult',
            name='away_runs',
        ),
        migrations.RemoveField(
            model_name='gameresult',
            name='away_score',
        ),
        migrations.RemoveField(
            model_name='gameresult',
            name='home_runs',
        ),
        migrations.RemoveField(
            model_name='gameresult',
            name='home_score',
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='away_errors',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='away_hits',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='home_errors',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='home_hits',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='InningScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.PositiveSmallIntegerField()),
                ('home_runs', models.PositiveSmallIntegerField(default=0)),
                ('away_runs', models.PositiveSmallIntegerField(default=0)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings', to='games.gameresult')),
            ],
            options={
                'ordering': ['inning'],
                'unique_together': {('result', 'inning')},
            },
        ),
    ]
