# Generated by Django 6.0.7 on 2026-08-27 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_alter_gameresult_away_errors_and_more'),
        ('teams', '0002_competition_legacyteamidentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='games', to='teams.competition'),
        ),
        migrations.AddField(
            model_name='game',
            name='exclude_from_standings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='legacy_game_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='final_away_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='final_home_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='innings_played',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LegacyGameIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_game_id', models.PositiveBigIntegerField(unique=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_identity', to='games.game')),
            ],
        ),
    ]
