# Generated by Django 6.0.7 on 2026-07-27 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0011_alter_gameresult_away_errors_and_more'),
        ('players', '0002_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineups_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_session', to='games.game')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_scoring_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batting_index', models.PositiveSmallIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_lineups', to='game_entry.scoringsession')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_lineups', to='teams.team')),
            ],
            options={
                'unique_together': {('session', 'team')},
            },
        ),
        migrations.CreateModel(
            name='PlateAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('1B', 'Single'), ('2B', 'Double'), ('3B', 'Triple'), ('HR', 'Home Run'), ('BB', 'Walk'), ('K', 'Strikeout'), ('OUT', 'Out'), ('HBP', 'Hit By Pitch'), ('E', 'Reached on Error'), ('SAC', 'Sacrifice'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plate_appearances', to='players.player')),
                ('offense_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plate_appearances', to='teams.team')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_plate_appearances', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plate_appearances', to='game_entry.scoringsession')),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plate_appearances', to='game_entry.teamlineup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LineupSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batting_order', models.PositiveSmallIntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_spots', to='players.player')),
                ('team_lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='game_entry.teamlineup')),
            ],
            options={
                'ordering': ['batting_order'],
                'unique_together': {('team_lineup', 'batting_order'), ('team_lineup', 'player')},
            },
        ),
    ]
