# Generated by Django 6.0.7 on 2026-07-28 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_entry', '0001_initial'),
        ('players', '0002_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plateappearance',
            name='first_base_runner_before',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plate_appearances_first_base_before', to='players.player'),
        ),
        migrations.AddField(
            model_name='plateappearance',
            name='half_inning',
            field=models.CharField(choices=[('TOP', 'Top'), ('BOT', 'Bottom')], default='TOP', max_length=3),
        ),
        migrations.AddField(
            model_name='plateappearance',
            name='inning_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plateappearance',
            name='outs_before',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plateappearance',
            name='second_base_runner_before',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plate_appearances_second_base_before', to='players.player'),
        ),
        migrations.AddField(
            model_name='plateappearance',
            name='third_base_runner_before',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plate_appearances_third_base_before', to='players.player'),
        ),
        migrations.AddField(
            model_name='scoringsession',
            name='current_inning',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='scoringsession',
            name='first_base_runner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_on_first_base', to='players.player'),
        ),
        migrations.AddField(
            model_name='scoringsession',
            name='half_inning',
            field=models.CharField(choices=[('TOP', 'Top'), ('BOT', 'Bottom')], default='TOP', max_length=3),
        ),
        migrations.AddField(
            model_name='scoringsession',
            name='outs',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoringsession',
            name='second_base_runner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_on_second_base', to='players.player'),
        ),
        migrations.AddField(
            model_name='scoringsession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoringsession',
            name='third_base_runner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_on_third_base', to='players.player'),
        ),
        migrations.CreateModel(
            name='LineupSubstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batting_order', models.PositiveSmallIntegerField()),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incoming_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subbed_in_events', to='players.player')),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='game_entry.teamlineup')),
                ('outgoing_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subbed_out_events', to='players.player')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_substitutions', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='game_entry.scoringsession')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_substitutions', to='teams.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
