# Generated by Django 6.0.7 on 2026-09-03 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_entry', '0002_plateappearance_first_base_runner_before_and_more'),
        ('games', '0012_game_competition_game_exclude_from_standings_and_more'),
        ('players', '0004_alter_roster_unique_together_and_more'),
        ('teams', '0002_competition_legacyteamidentity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineupsubstitution',
            name='incoming_player',
        ),
        migrations.RemoveField(
            model_name='lineupsubstitution',
            name='lineup',
        ),
        migrations.RemoveField(
            model_name='lineupsubstitution',
            name='outgoing_player',
        ),
        migrations.RemoveField(
            model_name='lineupsubstitution',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='lineupsubstitution',
            name='session',
        ),
        migrations.RemoveField(
            model_name='lineupsubstitution',
            name='team',
        ),
        migrations.RemoveField(
            model_name='plateappearance',
            name='batter',
        ),
        migrations.RemoveField(
            model_name='plateappearance',
            name='first_base_runner_before',
        ),
        migrations.RemoveField(
            model_name='plateappearance',
            name='lineup',
        ),
        migrations.RemoveField(
            model_name='plateappearance',
            name='offense_team',
        ),
        migrations.RemoveField(
            model_name='plateappearance',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='plateappearance',
            name='second_base_runner_before',
        ),
        migrations.RemoveField(
            model_name='plateappearance',
            name='session',
        ),
        migrations.RemoveField(
            model_name='plateappearance',
            name='third_base_runner_before',
        ),
        migrations.RemoveField(
            model_name='scoringsession',
            name='first_base_runner',
        ),
        migrations.RemoveField(
            model_name='scoringsession',
            name='game',
        ),
        migrations.RemoveField(
            model_name='scoringsession',
            name='second_base_runner',
        ),
        migrations.RemoveField(
            model_name='scoringsession',
            name='started_by',
        ),
        migrations.RemoveField(
            model_name='scoringsession',
            name='third_base_runner',
        ),
        migrations.AlterUniqueTogether(
            name='teamlineup',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='teamlineup',
            name='session',
        ),
        migrations.RemoveField(
            model_name='teamlineup',
            name='team',
        ),
        migrations.CreateModel(
            name='GameScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayed_innings', models.PositiveSmallIntegerField(default=9)),
                ('is_finalized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scorecards', to=settings.AUTH_USER_MODEL)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scorecard', to='games.game')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BattingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_slots', to='players.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecard_batting_slots', to='teams.team')),
                ('scorecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_slots', to='game_entry.gamescorecard')),
            ],
            options={
                'ordering': ['team_id', 'order'],
                'unique_together': {('scorecard', 'team', 'order'), ('scorecard', 'team', 'player')},
            },
        ),
        migrations.CreateModel(
            name='ScorecardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.PositiveSmallIntegerField(default=1)),
                ('half_inning', models.CharField(choices=[('TOP', 'Top'), ('BOT', 'Bottom')], default='TOP', max_length=3)),
                ('play_index', models.PositiveSmallIntegerField(default=1)),
                ('result', models.CharField(choices=[('1B', 'Single'), ('2B', 'Double'), ('3B', 'Triple'), ('HR', 'Home Run'), ('BB', 'Walk'), ('K', 'Strikeout'), ('OUT', 'Out'), ('HBP', 'Hit By Pitch'), ('E', 'Reached on Error'), ('FC', "Fielder's Choice"), ('SAC', 'Sacrifice'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('outs_recorded', models.PositiveSmallIntegerField(default=0)),
                ('rbi', models.PositiveSmallIntegerField(default=0)),
                ('batter_ending_base', models.CharField(choices=[('1B', '1st Base'), ('2B', '2nd Base'), ('3B', '3rd Base'), ('HOME', 'Scored'), ('OUT', 'Out')], default='OUT', max_length=4)),
                ('runner_1st_ending', models.CharField(blank=True, choices=[('1B', '1st Base'), ('2B', '2nd Base'), ('3B', '3rd Base'), ('HOME', 'Scored'), ('OUT', 'Out')], max_length=4)),
                ('runner_2nd_ending', models.CharField(blank=True, choices=[('1B', '1st Base'), ('2B', '2nd Base'), ('3B', '3rd Base'), ('HOME', 'Scored'), ('OUT', 'Out')], max_length=4)),
                ('runner_3rd_ending', models.CharField(blank=True, choices=[('1B', '1st Base'), ('2B', '2nd Base'), ('3B', '3rd Base'), ('HOME', 'Scored'), ('OUT', 'Out')], max_length=4)),
                ('notation', models.CharField(blank=True, max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_scorecard_entries', to=settings.AUTH_USER_MODEL)),
                ('runner_1st_before', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='players.player')),
                ('runner_2nd_before', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='players.player')),
                ('runner_3rd_before', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='players.player')),
                ('scorecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='game_entry.gamescorecard')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='game_entry.battingslot')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecard_entries', to='teams.team')),
            ],
            options={
                'ordering': ['team_id', 'inning', 'half_inning', 'play_index'],
                'unique_together': {('scorecard', 'team', 'inning', 'half_inning', 'play_index')},
            },
        ),
        migrations.DeleteModel(
            name='LineupSpot',
        ),
        migrations.DeleteModel(
            name='LineupSubstitution',
        ),
        migrations.DeleteModel(
            name='PlateAppearance',
        ),
        migrations.DeleteModel(
            name='ScoringSession',
        ),
        migrations.DeleteModel(
            name='TeamLineup',
        ),
    ]
