# Generated by Django 6.0.7 on 2026-09-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_newslettercampaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettercampaign',
            name='html_body',
            field=models.TextField(blank=True, help_text='Optional HTML body. Falls back to the plain-text body if left blank.'),
        ),
        migrations.AlterField(
            model_name='newslettercampaign',
            name='text_body',
            field=models.TextField(blank=True, help_text='Plain-text body. Required unless HTML body is filled in.'),
        ),
    ]
