# Generated by Django 6.0.7 on 2026-07-11 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.season'),
        ),
        migrations.AddField(
            model_name='roster',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.AlterUniqueTogether(
            name='roster',
            unique_together={('player', 'team', 'season')},
        ),
    ]
