# Generated by Django 6.0.7 on 2026-08-27 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_initial'),
        ('teams', '0002_competition_legacyteamidentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='teams.competition'),
        ),
        migrations.CreateModel(
            name='LegacyPlayerIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_player_id', models.PositiveBigIntegerField(unique=True)),
                ('source_first_name', models.CharField(blank=True, max_length=50)),
                ('source_last_name', models.CharField(blank=True, max_length=50)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_identities', to='players.player')),
            ],
        ),
    ]
