# Generated by Django 6.0.7 on 2026-08-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_roster_competition_legacyplayeridentity'),
        ('teams', '0002_competition_legacyteamidentity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roster',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='roster',
            constraint=models.UniqueConstraint(fields=('player', 'team', 'season', 'competition'), name='unique_player_team_season_competition'),
        ),
    ]
