# Generated by Django 6.0.7 on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_alter_roster_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='show_in_team_list',
            field=models.BooleanField(default=True),
        ),
    ]