# Generated by Django 6.0.7 on 2026-09-03 05:16

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Sanitized HTML body.'),
        ),
    ]
