# Generated by Django 6.0.7 on 2026-08-27 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phase', models.CharField(choices=[('REGULAR', 'Regular Season'), ('PLAYOFFS', 'Playoffs'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('legacy_division_id', models.PositiveBigIntegerField(blank=True, null=True, unique=True)),
                ('source_order', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_team_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='teams.season')),
            ],
            options={
                'ordering': ['-season__year', 'source_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LegacyTeamIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_team_id', models.PositiveBigIntegerField(unique=True)),
                ('source_name', models.CharField(max_length=100)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_team_identities', to='teams.competition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_identities', to='teams.team')),
            ],
        ),
    ]
